package translator

import "sync"

var (
	hotWordsToEn = map[string]string{
		"红色":    "red",
		"蓝色":    "blue",
		"黑色":    "black",
		"白色":    "white",
		"绿色":    "green",
		"黄色":    "yellow",
		"紫色":    "purple",
		"粉色":    "pink",
		"橙色":    "orange",
		"灰色":    "gray",
		"棕色":    "brown",
		"金色":    "gold",
		"银色":    "silver",
		"连衣裙":   "dress",
		"T 恤":   "t-shirt",
		"衬衫":    "shirt",
		"裤子":    "pants",
		"裙子":    "skirt",
		"外套":    "jacket",
		"大衣":    "coat",
		"毛衣":    "sweater",
		"运动鞋":   "sneakers",
		"皮鞋":    "leather shoes",
		"靴子":    "boots",
		"凉鞋":    "sandals",
		"拖鞋":    "slippers",
		"手机":    "phone",
		"电脑":    "computer",
		"笔记本":   "laptop",
		"平板":    "tablet",
		"耳机":    "headphones",
		"音响":    "speaker",
		"相机":    "camera",
		"电视":    "tv",
		"冰箱":    "refrigerator",
		"洗衣机":   "washer",
		"空调":    "ac",
		"风扇":    "fan",
		"电饭煲":   "rice cooker",
		"微波炉":   "microwave",
		"吸尘器":   "vacuum",
		"电吹风":   "hair dryer",
		"剃须刀":   "shaver",
		"榨汁机":   "juicer",
		"咖啡机":   "coffee machine",
		"热水壶":   "kettle",
		"手表":    "watch",
		"项链":    "necklace",
		"耳环":    "earrings",
		"戒指":    "ring",
		"手镯":    "bracelet",
		"包":     "bag",
		"背包":    "backpack",
		"钱包":    "wallet",
		"皮带":    "belt",
		"围巾":    "scarf",
		"帽子":    "hat",
		"手套":    "gloves",
		"袜子":    "socks",
		"领带":    "tie",
		"女士":    "women",
		"男士":    "men",
		"儿童":    "kids",
		"婴幼儿":   "baby",
		"新款":    "new",
		"特价":    "sale",
		"热销":    "hot",
		"爆款":    "bestseller",
		"正品":    "authentic",
		"正品保证":  "guaranteed authentic",
		"包邮":    "free shipping",
		"七天无理由": "7-day return",
		"限时折扣":  "limited discount",
		"优惠券":   "coupon",
		"满减":    "discount",
		"套装":    "set",
		"单品":    "single item",
		"加大码":   "plus size",
		"小码":    "small size",
		"大码":    "large size",
		"中码":    "medium size",
		"修身":    "slim fit",
		"宽松":    "loose fit",
		"紧身":    "tight fit",
		"休闲":    "casual",
		"正装":    "formal",
		"运动":    "sports",
		"潮流":    "trendy",
		"复古":    "vintage",
		"简约":    "simple",
		"时尚":    "fashion",
		"可爱":    "cute",
		"优雅":    "elegant",
		"商务":    "business",
		"学生":    "student",
		"上班":    "work",
		"约会":    "date",
		"派对":    "party",
		"旅行":    "travel",
		"户外":    "outdoor",
		"居家":    "home",
		"睡眠":    "sleep",
		"健身":    "fitness",
		"瑜伽":    "yoga",
		"跑步":    "running",
		"游泳":    "swimming",
		"骑行":    "cycling",
		"登山":    "hiking",
		"滑雪":    "skiing",
		"毛绒":    "plush",
		"棉质":    "cotton",
		"丝绸":    "silk",
		"羊毛":    "wool",
		"皮革":    "leather",
		"牛仔":    "denim",
		"针织":    "knitted",
		"梭织":    "woven",
		"纯棉":    "pure cotton",
		"涤纶":    "polyester",
		"亚麻":    "linen",
		"羊绒":    "cashmere",
		"仿真丝":   "faux silk",
		"雪纺":    "chiffon",
		"蕾丝":    "lace",
		"绒布":    "flannel",
		"帆布":    "canvas",
		"磨毛":    "brushed",
		"水洗":    "washed",
		"免烫":    "wrinkle free",
		"防水":    "waterproof",
		"防风":    "windproof",
		"保暖":    "warm",
		"透气":    "breathable",
		"轻薄":    "lightweight",
		"厚实":    "thick",
		"柔软":    "soft",
		"硬朗":    "sturdy",
		"光滑":    "smooth",
		"粗糙":    "rough",
		"亮面":    "glossy",
		"哑光":    "matte",
		"拼接":    "splicing",
		"印花":    "print",
		"绣花":    "embroidery",
		"烫金":    "foil stamping",
		"植绒":    "flocking",
		"水钻":    "rhinestone",
		"珍珠":    "pearl",
		"宝石":    "gem",
		"水晶":    "crystal",
		"陶瓷":    "ceramic",
		"木质":    "wooden",
		"金属":    "metal",
		"塑料":    "plastic",
		"玻璃":    "glass",
		"竹制":    "bamboo",
		"藤编":    "wicker",
		"收纳":    "storage",
		"整理":    "organization",
		"清洁":    "cleaning",
		"厨具":    "cookware",
		"餐具":    "tableware",
		"灯具":    "lamp",
		"装饰":    "decor",
		"礼品":    "gift",
		"文具":    "stationery",
		"美妆":    "beauty",
		"护肤":    "skincare",
		"彩妆":    "makeup",
		"香水":    "perfume",
		"身体护理":  "body care",
		"口腔护理":  "oral care",
		"头发护理":  "hair care",
		"男士护理":  "men's care",
		"美容工具":  "beauty tools",
		"保健":    "health",
		"营养":    "nutrition",
		"零食":    "snacks",
		"饮料":    "drinks",
		"生鲜":    "fresh food",
		"水果":    "fruits",
		"蔬菜":    "vegetables",
		"肉":     "meat",
		"海鲜":    "seafood",
		"母婴":    "mother baby",
		"童装":    "children's clothing",
		"童鞋":    "children's shoes",
		"玩具":    "toys",
		"奶粉":    "milk powder",
		"尿不湿":   "diaper",
		"推车":    "stroller",
		"安全座椅":  "car seat",
		"家具":    "furniture",
		"床":     "bed",
		"床垫":    "mattress",
		"枕头":    "pillow",
		"被子":    "quilt",
		"四件套":   "bedding set",
		"窗帘":    "curtain",
		"地毯":    "carpet",
		"挂画":    "painting",
		"摆件":    "ornament",
		"时钟":    "clock",
		"收纳箱":   "storage box",
		"衣架":    "hanger",
		"晾衣架":   "clothes rack",
		"垃圾桶":   "trash can",
		"拖把":    "mop",
		"扫帚":    "broom",
		"抹布":    "rag",
		"洗涤剂":   "detergent",
		"纸巾":    "tissue",
		"湿巾":    "wet wipes",
		"卫生纸":   "toilet paper",
		"垃圾袋":   "garbage bags",
		"挂钩":    "hook",
		"置物架":   "shelf",
		"花盆":    "flower pot",
		"绿植":    "green plant",
		"仿真花":   "artificial flower",
		"香薰":    "aromatherapy",
		"蜡烛":    "candle",
		"床品":    "bedding",
		"套件":    "set",
		"枕套":    "pillowcase",
		"被套":    "quilt cover",
		"床单":    "sheet",
		"抱枕":    "cushion",
		"靠垫":    "back cushion",
		"沙发垫":   "sofa cushion",
		"地垫":    "floor mat",
		"门垫":    "door mat",
		"空调被":   "air conditioning quilt",
		"夏被":    "summer quilt",
		"冬被":    "winter quilt",
		"鹅绒被":   "eiderdown quilt",
		"蚕丝被":   "silk quilt",
		"棉被":    "cotton quilt",
		"纤维被":   "fiber quilt",
		"羽绒被":   "down quilt",
		"羊毛被":   "wool quilt",
	}

	// 英文到中文的反向映射（自动生成）
	hotWordsToCn = map[string]string{}
	// 确保只初始化一次
	initOnce sync.Once
)

// initHotWords 初始化反向映射，在首次使用时自动调用
func initHotWords() {
	initOnce.Do(func() {
		// 从中文到英文的映射生成反向映射
		for cn, en := range hotWordsToEn {
			hotWordsToCn[en] = cn
		}
	})
}
